export const translateTypes = {
  ice: 'Gelo',
  steel: 'Aço',
  fire: 'Fogo',
  bug: 'Inseto',
  fairy: 'Fada',
  water: 'Água',
  flying: 'Vòo',
  rock: 'Pedra',
  dark: 'Escuro',
  grass: 'Grama',
  ground: 'Solo',
  dragon: 'Dragão',
  normal: 'Normal',
  poison: 'Tóxico',
  ghost: 'Fantasma',
  fighting: 'Combate',
  psychic: 'Psíquico',
  electric: 'Eletrico',
}
